// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: currency_exchange.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CurrencyExchange_GetExchangeRate_FullMethodName = "/currencyexchange.CurrencyExchange/GetExchangeRate"
)

// CurrencyExchangeClient is the client API for CurrencyExchange service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CurrencyExchangeClient interface {
	GetExchangeRate(ctx context.Context, in *ExchangeRateRequest, opts ...grpc.CallOption) (*ExchangeRateResponse, error)
}

type currencyExchangeClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyExchangeClient(cc grpc.ClientConnInterface) CurrencyExchangeClient {
	return &currencyExchangeClient{cc}
}

func (c *currencyExchangeClient) GetExchangeRate(ctx context.Context, in *ExchangeRateRequest, opts ...grpc.CallOption) (*ExchangeRateResponse, error) {
	out := new(ExchangeRateResponse)
	err := c.cc.Invoke(ctx, CurrencyExchange_GetExchangeRate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrencyExchangeServer is the server API for CurrencyExchange service.
// All implementations must embed UnimplementedCurrencyExchangeServer
// for forward compatibility
type CurrencyExchangeServer interface {
	GetExchangeRate(context.Context, *ExchangeRateRequest) (*ExchangeRateResponse, error)
	mustEmbedUnimplementedCurrencyExchangeServer()
}

// UnimplementedCurrencyExchangeServer must be embedded to have forward compatible implementations.
type UnimplementedCurrencyExchangeServer struct {
}

func (UnimplementedCurrencyExchangeServer) GetExchangeRate(context.Context, *ExchangeRateRequest) (*ExchangeRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExchangeRate not implemented")
}
func (UnimplementedCurrencyExchangeServer) mustEmbedUnimplementedCurrencyExchangeServer() {}

// UnsafeCurrencyExchangeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrencyExchangeServer will
// result in compilation errors.
type UnsafeCurrencyExchangeServer interface {
	mustEmbedUnimplementedCurrencyExchangeServer()
}

func RegisterCurrencyExchangeServer(s grpc.ServiceRegistrar, srv CurrencyExchangeServer) {
	s.RegisterService(&CurrencyExchange_ServiceDesc, srv)
}

func _CurrencyExchange_GetExchangeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyExchangeServer).GetExchangeRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyExchange_GetExchangeRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyExchangeServer).GetExchangeRate(ctx, req.(*ExchangeRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CurrencyExchange_ServiceDesc is the grpc.ServiceDesc for CurrencyExchange service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CurrencyExchange_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "currencyexchange.CurrencyExchange",
	HandlerType: (*CurrencyExchangeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExchangeRate",
			Handler:    _CurrencyExchange_GetExchangeRate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "currency_exchange.proto",
}
